### ISSUE TITLE
Update changelog?

### ISSUE THREAD

**Issue by mperham** [ruby/logger#96]
There are undocumented versions not in the changelog. If you want a native English speaker, I would be glad to volunteer.

**Comment by hsbt** [comment]
Thanks for your friendly support. Maintaining CHANGELOG is:

* Easily conflict pull-request like https://github.com/ruby/logger/pull/73
* It makes release work hard. Because `gh releases` can't work before `git tag`. It's not useful with `rake release` with bundler task.

But I would like to switch https://github.com/ruby/logger/releases/ from CHANGELOG.

**Comment by mperham** [comment]
I understand, thanks.
